### ISSUE TITLE
typeNameToClass throws exception instead of callback onClassNotFound

### ISSUE THREAD

**Issue by mhoennig** [mhoennig/columbo#3]
java.lang.NoClassDefFoundError: B[some referenced class references from A]
    at A[some business class from classpath].<clinit>(DataRestrictionCategoryType.java:44)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:169)
    at de.javagil.columbo.internal.BytecodeUtil.typeNameToClass(BytecodeUtil.java:170)
    at de.javagil.columbo.internal.BytecodeUtil.taggedTypeNameToClass(BytecodeUtil.java:133)
    at de.javagil.columbo.internal.BytecodeUtil.determineParameterTypes(BytecodeUtil.java:112)
    at de.javagil.columbo.internal.ClassVisitor.visitMethod(ClassVisitor.java:90)
    at de.javagil.columbo.internal.ClassVisitor.visitMethod(ClassVisitor.java:52)
    at org.objectweb.asm.ClassReader.accept(Unknown Source)
    at org.objectweb.asm.ClassReader.accept(Unknown Source)
    at de.javagil.columbo.internal.ClassVisitor.getReferersOfClassName(ClassVisitor.java:131)
    at de.javagil.columbo.internal.ClassVisitor.inspect(ClassVisitor.java:122)
    at de.javagil.columbo.api.BytecodeInspector.inspect(BytecodeInspector.java:77)

**Comment by mhoennig** [comment]
fixed with https://github.com/mhoennig/columbo/commit/0edf3e9a1ee5ac3fca71e62cb849fb74c2f28bb5
